# Generated by Django 5.2.4 on 2025-08-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coaches',
            fields=[
                ('CoachId', models.AutoField(primary_key=True, serialize=False)),
                ('CoachName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('MemberId', models.AutoField(primary_key=True, serialize=False)),
                ('MemberName', models.CharField(max_length=100)),
                ('Coach', models.CharField(max_length=100)),
                ('DateOfJoin', models.DateField()),
                ('PhotoFileName', models.CharField(max_length=100)),
            ],
        ),
    ]
